<Project Sdk="Godot.NET.Sdk/4.5.1" InitialTargets="CheckDependencyPaths">
    <Import Project=".\Sts2PathDiscovery.props"/>
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>true</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <AppOutputBase>$(MSBuildProjectDirectory)\</AppOutputBase>
        <PathMap>$(AppOutputBase)=.\</PathMap>
        <GodotDisabledSourceGenerators>GodotPluginsInitializer</GodotDisabledSourceGenerators>
    </PropertyGroup>

    <PropertyGroup>
        <NoWarn>$(NoWarn);MSB3270</NoWarn> 
    </PropertyGroup>

    <ItemGroup Condition="Exists('$(Sts2DataDir)')">
        <Reference Include="0Harmony">
            <HintPath>$(Sts2DataDir)/0Harmony.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="sts2">
            <HintPath>$(Sts2DataDir)/sts2.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>
    
    <ItemGroup Condition="True">
        <Publicize Include="sts2" IncludeVirtualMembers="false" IncludeCompilerGeneratedMembers="false" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Alchyr.Sts2.BaseLib" Version="*" PrivateAssets="All"/>
        <PackageReference Include="Krafs.Publicizer" Version="2.3.0" PrivateAssets="All"/>
        <PackageReference Include="Alchyr.Sts2.ModAnalyzers" Version="*" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="materials/**" />
        <Compile Remove="shaders/**" />
        <Compile Remove="images/**" />
        <EmbeddedResource Remove="materials/**" />
        <EmbeddedResource Remove="shaders/**" />
        <EmbeddedResource Remove="images/**" />
    </ItemGroup>

    <ItemGroup>
        <None Condition="Exists('Directory.Build.props')" Include="Directory.Build.props"/>
        <None Include="DataDumper.json" />
        <None Include="project.godot"/>
    </ItemGroup>
    
    <Target Name="CheckDependencyPaths">
        <Error
                Text=" Slay the Spire 2 data not found at path '$(Sts2DataDir)'"
                Condition="'$(Sts2DataDir)' == '' or !Exists('$(Sts2DataDir)')" />
    </Target>

    <Target Name="CopyToModsFolderOnBuild" AfterTargets="PostBuildEvent">
        <Message Text="Copying .dll .pdb and .json to mods folder." Importance="high" />
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ModsPath)$(MSBuildProjectName)/" />
        <Copy SourceFiles="$(AssemblyName).json" DestinationFolder="$(ModsPath)$(MSBuildProjectName)/" />
        <Copy SourceFiles="$(TargetDir)$(TargetName).pdb" DestinationFolder="$(ModsPath)$(MSBuildProjectName)/" />
    </Target>
</Project>