#!/usr/bin/env python3
"""Generate crates/sts2sim/src/ids.rs from the decompiled game source.

Ids are dense u16 indices assigned in ordinal order of the game's ModelId entry (the slugified class
name), so comparing ids == comparing ModelIds (the game sorts cards by ModelId on reshuffle).
Usage: tools/gen_ids.py [decomp_root] > crates/sts2sim/src/ids.rs
"""
import glob, os, re, sys

ROOT = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), "..", "decomp")
MODELS = os.path.join(ROOT, "MegaCrit/Sts2/Core/Models")


def slugify(name: str) -> str:
    """StringHelper.Slugify: Regex.Replace(name, @"([A-Za-z0-9]|\\G(?!^))([A-Z])", "$1_$2") then upper."""
    out, i, n = [], 0, len(name)
    last_end = -1  # end of previous match (for \G)
    while i < n:
        # alternative 1: [A-Za-z0-9] followed by [A-Z]
        if i + 1 < n and name[i].isascii() and name[i].isalnum() and "A" <= name[i + 1] <= "Z":
            out.append(f"{name[i]}_{name[i+1]}")
            i += 2
            last_end = i
            continue
        # alternative 2: \G(?!^) then [A-Z]
        if i == last_end and i != 0 and "A" <= name[i] <= "Z":
            out.append(f"_{name[i]}")
            i += 1
            last_end = i
            continue
        out.append(name[i])
        i += 1
    return "".join(out).upper()


def classes(subdir, base_pattern=None):
    names = []
    for path in sorted(glob.glob(os.path.join(MODELS, subdir, "*.cs"))):
        src = open(path, encoding="utf-8-sig").read()
        for m in re.finditer(r"public\s+(?:sealed\s+|abstract\s+|static\s+)*class\s+(\w+)\s*(?::\s*([\w<>, .]+))?", src):
            full = m.group(0)
            if "abstract" in full or "static" in full:
                continue
            names.append(m.group(1))
    return sorted(set(names))


CATEGORIES = [
    ("card", "Cards"),
    ("power", "Powers"),
    ("relic", "Relics"),
    ("potion", "Potions"),
    ("monster", "Monsters"),
    ("encounter", "Encounters"),
    ("enchantment", "Enchantments"),
    ("orb", "Orbs"),
    ("affliction", "Afflictions"),
]

print("// @generated by tools/gen_ids.py from the decompiled game source. Do not edit.")
print("// Ids are dense and ordered by the ordinal order of the game's ModelId entry (slugified class name).")
print("#![allow(dead_code)]\n")
for mod, sub in CATEGORIES:
    if not os.path.isdir(os.path.join(MODELS, sub)):
        continue
    entries = sorted({(slugify(n), n) for n in classes(sub)}, key=lambda t: t[0].encode("ascii"))
    print(f"pub mod {mod} {{")
    print(f"    pub const COUNT: usize = {len(entries)};")
    print(f"    /// ModelId entry strings (e.g. `STRIKE_IRONCLAD`), indexed by id.")
    print("    pub static NAMES: [&str; COUNT] = [")
    for slug, _ in entries:
        print(f'        "{slug}",')
    print("    ];")
    print("    /// C# class names, indexed by id.")
    print("    pub static CLASS_NAMES: [&str; COUNT] = [")
    for _, cls in entries:
        print(f'        "{cls}",')
    print("    ];")
    for i, (slug, _) in enumerate(entries):
        const = slug if not slug[0].isdigit() else "_" + slug
        print(f"    pub const {const}: u16 = {i};")
    print("}\n")
