import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from common import AL, SOURCE, deck

EEL = "TERROR_EEL_ELITE"
SPEC = dict(
    id="hMrQSndDvPc_F09_TERROR_EEL_ELITE",
    aliases=AL,
    enemy_ids=["TERROR_EEL"],
    source=dict(SOURCE, floor=9, video_span="5:08-7:04"),
    scenario=dict(name="baalorlord", ascension=10, encounter=EEL, character="SILENT", hp=35, max_hp=70, max_energy=3, gold=79,
                  max_potion_slots=2, base_orb_slots=0, seed="placeholder", total_floor=9, act=0,
                  deck=deck(("S", 5), ("D", 5), ("N", 1), ("SV", 1), ("AB", 1), ("DS+", 1), ("DA", 1), ("HD", 1), ("CL", 1), ("SB", 1)),
                  relics=[{"id": "RING_OF_THE_SNAKE"}, {"id": "SILKEN_TRESS", "props": {"IsUsed": True}}, {"id": "CENTENNIAL_PUZZLE"},
                          {"id": "PEN_NIB", "counter": 0}],
                  potions=[{"id": "DEXTERITY_POTION", "slot": 0}, {"id": "CUNNING_POTION", "slot": 1}]),
    turns=[
        dict(obs=dict(hp=35, block=0, energy=3, hand=["N", "AB", "S", "D", "D", "DA", "D"], draw_n=11, relics={"PEN_NIB": 0},
                      e=[dict(hp=150, powers={"SHRIEK_POWER": 75}, intent=[("Attack", 18, 1)])]),
             times=["5:20", "5:21", "5:22", "5:24", "5:25"],
             acts=[("pot", 0, None), ("p", "N", 0), ("p", "DA", 0, dict(block=12, e=[dict(hp=137)])), ("p", "S", 0, dict(e=[dict(hp=131)])),
                   ("e",)]),
        dict(obs=dict(hp=34, block=0, energy=3, hand=["D", "SV", "SB", "CL", "S", "D", "S", "S"], draw_n=3, relics={"PEN_NIB": 3},
                      e=[dict(hp=131, intent=[("Attack", 4, 3), ("Buff",)])]),
             times=["5:36", "5:37", "5:38", "5:39"],
             acts=[("p", "SB", 0), ("p", "SV"), ("c", "S"), ("e",)]),
        dict(obs=dict(hp=32, block=0, energy=3, hand=["S", "HD", "DS+", "S", "SV"], draw_n=11, relics={"PEN_NIB": 3},
                      e=[dict(hp=124, powers={"SHRIEK_POWER": 75, "POISON_POWER": 6, "VIGOR_POWER": 6}, intent=[("Attack", 24, 1)])]),
             times=["5:47", "5:53", "5:57", "6:06", "6:08", "6:14", "6:15", "6:17"],
             acts=[("p", "DS+", None, dict(e=[dict(hp=100)])), ("p", "S", 0, dict(e=[dict(hp=94)])), ("p", "SV"), ("c", "S", dict(block=10, draw=["D", "D", "D", "D", "D", "N", "S", "S", "S", "SB", "DA"])), ("p", "HD"),
                   ("p", "SH", 0), ("p", "SH", 0, dict(e=[dict(hp=86)])), ("e",)]),
        dict(obs=dict(hp=18, block=0, energy=3, hand=["N", "S", "D", "DA", "S"], relics={"PEN_NIB": 8},
                      e=[dict(hp=80, powers={"SHRIEK_POWER": 75, "POISON_POWER": 5}, intent=[("Attack", 4, 3), ("Buff",)])]),
             times=["6:25", "6:26", "6:27", "6:28"],
             acts=[("p", "N", 0), ("p", "DA", 0, dict(e=[dict(hp=57)])), ("p", "S@2", 0, dict(e=[dict(hp=51)])), ("e",)]),
        dict(obs=dict(hp=18, block=0, energy=3, hand=["D", "D", "D", "SB", "D"], draw_n=1, relics={"PEN_NIB": 1},
                      e=[dict(hp=46, powers={"POISON_POWER": 4}, intent=[("Debuff",)])]),
             times=["6:41", "6:44"],
             acts=[("p", "SB", 0), ("e",)]),
        dict(obs=dict(hp=18, block=0, energy=3, hand=["S", "HD", "S", "D", "SV"], draw_n=11, relics={"PEN_NIB": 1}, pp={"DEXTERITY_POWER": 2, "VULNERABLE_POWER": 99},
                      e=[dict(hp=35, powers={"POISON_POWER": 10}, intent=[("Attack", 27, 1)])]),
             times=["6:58", "6:59", "7:00", "7:01", "7:02", "7:03", "7:04", "7:05", "7:06"],
             acts=[("pot", 1, None), ("p", "SH+", 0), ("p", "SH+", 0, dict(e=[dict(hp=23)])), ("p", "SH+", 0, dict(e=[dict(hp=17)])),
                   ("p", "S", 0, dict(e=[dict(hp=11)])), ("p", "S", 0, dict(e=[dict(hp=5)])), ("p", "HD"),
                   ("p", "SH", 0), ("p", "SH", 0)]),
    ],
)
