//! The combat engine: `impl Combat` blocks split by subsystem.

mod action;
mod autoplay;
mod budget;
mod cardcmds;
mod cmds;
mod creature;
mod cost;
mod damage;
mod death;
mod determinize;
mod enchant;
mod energy;
mod history;
mod dispatch;
mod lifecycle;
mod monster;
mod necro;
mod pets;
mod orbs;
mod piles;
mod potion_gen;
mod potions;
mod play;
mod powers;
mod regent;
mod relic_cmds;
mod replay;
mod sync;
mod turn;

pub use creature::DamageResult;
pub use necro::{is_temporary_power, temporary_inner_power};
pub use damage::{calc_with, Attack, Mods, Results, Targeting};
pub use dispatch::*;
pub use cmds::Ask;
pub use replay::ReplayAnswer;
pub use action::{Action, ActionBuf, ACTION_SPACE, MAX_PICK};
pub use monster::{STUN_INTENTS, STUN_NODE};
pub use monster::{with_look_cache, LookCache, LookRow, LOOK_CACHE_ENTRIES, LOOK_H, LOOK_LEGACY, LOOK_NODES};
pub use turn::BASE_HAND_DRAW;
pub use cost::CostMods;
pub use sync::{EnemySync, HandSync, ObsCard, ObsEnemy, ObsRelic, RelicSync};
pub use play::RunResult;
pub use history::{HKind, HistEntry, HistLog, HIST_CAP};
pub use orbs::VALID_ORBS;
