//! Aligning a simulated combat with an observation of the real game (visible information only).
//!
//! A replay of the fight with the simulator's own random hidden state draws different cards than the real game did. These functions put the
//! simulator's *visible* state on the observed one (the hand and its costs, the creatures' HP / block / energy) without touching anything the
//! player cannot see: cards move between piles directly (no hooks fire), the draw / discard / exhaust orders stay random, no RNG stream is read
//! from the real game. After a sync the simulator is one sample of the player's belief about the fight.

use crate::state::*;
use crate::dec::Dec;
use crate::util::ArrayVec;
use crate::types::*;

/// One card of the observed hand.
#[derive(Clone, Copy, Debug)]
pub struct ObsCard {
    pub id: u16,
    pub upgrade: u8,
    /// Observed current energy cost, `None` when not observed (or an X-cost / unplayable card).
    pub cost: Option<i32>,
}

/// What `sync_hand` had to do (diagnostics: a replay that needs many of these has diverged from the real fight).
#[derive(Clone, Copy, Debug, Default)]
pub struct HandSync {
    pub from_draw: u16,
    pub from_discard: u16,
    pub from_exhaust: u16,
    /// Cards that were in no pile (generated by the real game, e.g. by an effect the simulator resolved differently).
    pub created: u16,
    /// Simulated hand cards the real hand does not contain (returned to the draw pile).
    pub returned: u16,
    /// Cost corrections applied.
    pub cost_fixes: u16,
}

impl Combat {
    /// Makes the hand equal to `obs` (same cards in the same order). Matching cards stay, surplus cards go back to the draw pile at a random
    /// position, missing cards are taken from the draw pile, else the discard pile, else the exhaust pile, else created.
    pub fn sync_hand(&mut self, obs: &[ObsCard]) -> HandSync {
        let mut rep = HandSync::default();
        let old: Vec<CardIdx> = self.player.hand.iter().copied().collect();
        let mut used = vec![false; old.len()];
        let mut slots: Vec<Option<CardIdx>> = vec![None; obs.len()];
        let mut missing: Vec<usize> = vec![];
        for (i, o) in obs.iter().enumerate() {
            let hit = old.iter().enumerate().position(|(j, &c)| !used[j] && self.cards[c as usize].id == o.id && self.cards[c as usize].upgrade == o.upgrade);
            match hit {
                Some(j) => {
                    used[j] = true;
                    slots[i] = Some(old[j]);
                }
                None => missing.push(i),
            }
        }
        for (j, &c) in old.iter().enumerate() {
            if !used[j] {
                self.player.hand.remove_value(c);
                let n = self.player.draw.len();
                let at = self.rng.shuffle.next_int((n + 1) as i32) as usize;
                self.player.draw.insert(at, c);
                self.cards[c as usize].pile = PileType::Draw as u8;
                rep.returned += 1;
            }
        }
        for i in missing {
            let o = obs[i];
            let mut found: Option<CardIdx> = None;
            for (pile, counter) in [(PileType::Draw, 0u8), (PileType::Discard, 1), (PileType::Exhaust, 2)] {
                let p = self.pile(pile);
                let cand = p.iter().copied().find(|&c| self.cards[c as usize].id == o.id && self.cards[c as usize].upgrade == o.upgrade);
                if let Some(c) = cand {
                    self.pile_mut(pile).remove_value(c);
                    match counter {
                        0 => rep.from_draw += 1,
                        1 => rep.from_discard += 1,
                        _ => rep.from_exhaust += 1,
                    }
                    found = Some(c);
                    break;
                }
            }
            if found.is_none() {
                found = self.new_card(o.id, o.upgrade);
                if found.is_some() {
                    rep.created += 1;
                }
            }
            slots[i] = found;
        }
        self.player.hand.clear();
        for c in slots.into_iter().flatten() {
            self.player.hand.push(c);
            self.cards[c as usize].pile = PileType::Hand as u8;
        }
        // costs: the observed cost wins over the simulator's own (random cost effects such as Snecko Eye roll differently)
        let hand: Vec<CardIdx> = self.player.hand.iter().copied().collect();
        for (c, o) in hand.iter().zip(obs.iter()) {
            if let Some(want) = o.cost {
                if want < 0 || self.card_def(*c).x_cost {
                    continue;
                }
                let have = self.card_cost(*c, true);
                if have != want {
                    // global modifiers sit on top of the local ones: move the local cost by the difference
                    let local = self.card_cost(*c, false);
                    let target = (local + want - have).max(0);
                    self.set_cost_this_combat(*c, target, false);
                    rep.cost_fixes += 1;
                }
            }
        }
        rep
    }

    /// Makes a visible pile (discard or exhaust) hold exactly the observed cards (compared as a multiset: its order carries no information). Surplus
    /// cards go to the draw pile at a random position; missing cards come from the draw pile, else the other visible pile, else are created. The draw pile
    /// is then whatever is left, which is what a player who tracks his deck knows about it.
    pub fn sync_pile(&mut self, pile: PileType, obs: &[ObsCard]) -> HandSync {
        use std::collections::HashMap;
        let mut rep = HandSync::default();
        let mut want: HashMap<(u16, u8), i32> = HashMap::new();
        for o in obs {
            *want.entry((o.id, o.upgrade)).or_insert(0) += 1;
        }
        let current: Vec<CardIdx> = self.pile(pile).iter().copied().collect();
        for c in current {
            let key = (self.cards[c as usize].id, self.cards[c as usize].upgrade);
            match want.get_mut(&key) {
                Some(n) if *n > 0 => *n -= 1,
                _ => {
                    self.pile_mut(pile).remove_value(c);
                    let n = self.player.draw.len();
                let at = self.rng.shuffle.next_int((n + 1) as i32) as usize;
                self.player.draw.insert(at, c);
                self.cards[c as usize].pile = PileType::Draw as u8;
                    rep.returned += 1;
                }
            }
        }
        let other = if pile == PileType::Discard { PileType::Exhaust } else { PileType::Discard };
        for ((id, up), n) in want {
            for _ in 0..n.max(0) {
                let mut found: Option<CardIdx> = None;
                for src in [PileType::Draw, other] {
                    let cand = self.pile(src).iter().copied().find(|&c| self.cards[c as usize].id == id && self.cards[c as usize].upgrade == up);
                    if let Some(c) = cand {
                        self.pile_mut(src).remove_value(c);
                        if src == PileType::Draw { rep.from_draw += 1 } else if src == PileType::Discard { rep.from_discard += 1 } else { rep.from_exhaust += 1 }
                        found = Some(c);
                        break;
                    }
                }
                if found.is_none() {
                    found = self.new_card(id, up);
                    if found.is_some() {
                        rep.created += 1;
                    }
                }
                if let Some(c) = found {
                    self.pile_mut(pile).push(c);
                    self.cards[c as usize].pile = pile as u8;
                }
            }
        }
        rep
    }

    /// Makes the draw pile hold exactly the observed cards as a multiset (the order is hidden): the player sees which cards are in it. A simulated card the
    /// real pile does not have (random generation / upgrade that the real game resolved on another card: Stoke, Discovery, Aggression ...) does not exist in the
    /// real game and leaves the combat; a surplus card of the same kind as a missing one is replaced by it. Missing cards are created at a random position.
    /// Call after the hand and the visible piles are synced (they are exact then, so the draw pile is what is left).
    pub fn sync_draw(&mut self, obs: &[ObsCard]) -> HandSync {
        use std::collections::HashMap;
        let mut rep = HandSync::default();
        let mut want: HashMap<(u16, u8), i32> = HashMap::new();
        for o in obs {
            *want.entry((o.id, o.upgrade)).or_insert(0) += 1;
        }
        let current: Vec<CardIdx> = self.player.draw.iter().copied().collect();
        let mut surplus: Vec<CardIdx> = vec![];
        for c in current {
            let key = (self.cards[c as usize].id, self.cards[c as usize].upgrade);
            match want.get_mut(&key) {
                Some(n) if *n > 0 => *n -= 1,
                _ => surplus.push(c),
            }
        }
        for ((id, up), n) in want {
            for _ in 0..n.max(0) {
                // a surplus card of the same kind is the observed card with a different upgrade level (the two games upgraded different random cards:
                // Stone Cracker, Aggression ...): replace it, so the pile does not grow
                if let Some(k) = surplus.iter().position(|&c| self.cards[c as usize].id == id) {
                    let c = surplus.remove(k);
                    self.player.draw.remove_value(c);
                    self.cards[c as usize].pile = PileType::None as u8;
                    self.cards[c as usize].flags |= cflag::REMOVED;
                }
                if let Some(c) = self.new_card(id, up) {
                    let len = self.player.draw.len();
                    let at = self.rng.shuffle.next_int((len + 1) as i32) as usize;
                    self.player.draw.insert(at, c);
                    self.cards[c as usize].pile = PileType::Draw as u8;
                    rep.created += 1;
                }
            }
        }
        // the hand and the visible piles were synced exactly, so a card left over in the draw pile is a phantom (a random generation / upgrade the real game
        // resolved on another card), whatever its origin
        for c in surplus {
            self.player.draw.remove_value(c);
            self.cards[c as usize].pile = PileType::None as u8;
            self.cards[c as usize].flags |= cflag::REMOVED;
            rep.returned += 1;
        }
        rep
    }

    /// Puts a creature's powers on the observed ones (id, amount): the amounts of powers both have are set, powers the real creature does not have are dropped
    /// (no hooks), powers only the real creature has are applied. The two games resolve hidden draws and random targets differently (Hellraiser auto-plays
    /// the Strikes it draws: Slippery 9 -> 6, 7 or 8 depending on the shuffle), and the player sees the result. Returns how many powers were changed.
    pub fn sync_powers(&mut self, cid: Cid, obs: &[(u16, i32)]) -> u16 {
        let mut changed = 0u16;
        let mut left: Vec<Option<(u16, i32)>> = obs.iter().map(|&o| Some(o)).collect();
        let current: Vec<(u16, u16, i32)> = self.cr(cid).powers.iter().map(|p| (p.uid, p.id, p.amount)).collect();
        for (uid, id, amount) in current {
            let hit = left.iter().position(|o| matches!(o, Some((oid, _)) if *oid == id));
            match hit {
                Some(k) => {
                    let (_, want) = left[k].take().unwrap();
                    if want != amount {
                        if let Some(i) = self.power_idx(cid, uid) {
                            self.cr_mut(cid).powers[i].amount = want;
                            changed += 1;
                        }
                    }
                }
                None => {
                    if let Some(i) = self.power_idx(cid, uid) {
                        self.cr_mut(cid).powers.remove(i);
                        self.sync_secondary(cid);
                        changed += 1;
                    }
                }
            }
        }
        for (id, amount) in left.into_iter().flatten() {
            if amount != 0 && self.apply_power(id, cid, Dec::int(amount as i64), cid, NO).is_some() {
                changed += 1;
            }
        }
        changed
    }

    /// Puts the powers' `amount_on_turn_start` (the stack the creature had when its turn started, which the game exports) on the observed values, for the powers both
    /// sides have. `sync_powers` copies only (id, amount): a power the real creature got from a random effect the simulator resolved differently (Stampede picking Bash
    /// where the simulator played Strike) is created here with 0, which the diff then reported as a divergence and voided the advice.
    pub fn sync_turn_start(&mut self, cid: Cid, obs: &[(u16, i32)]) {
        let mut left: Vec<Option<(u16, i32)>> = obs.iter().map(|&o| Some(o)).collect();
        let ids: Vec<(u16, u16)> = self.cr(cid).powers.iter().map(|p| (p.uid, p.id)).collect();
        for (uid, id) in ids {
            if let Some(k) = left.iter().position(|o| matches!(o, Some((oid, _)) if *oid == id)) {
                let (_, v) = left[k].take().unwrap();
                if let Some(i) = self.power_idx(cid, uid) {
                    self.cr_mut(cid).powers[i].amount_on_turn_start = v;
                }
            }
        }
    }

    /// Sets a creature's visible numbers (HP, max HP, block). `cid` is the creature id (0 = player).
    pub fn sync_creature(&mut self, cid: Cid, hp: i32, max_hp: i32, block: i32) {
        let c = self.cr_mut(cid);
        c.hp = hp;
        c.max_hp = max_hp;
        c.block = block;
    }

    /// Sets the player's energy and stars.
    pub fn sync_energy(&mut self, energy: i32, stars: i32) {
        self.player.energy = energy;
        self.player.stars = stars;
    }

    /// Puts the enemy list on the observed one (the game's order) and returns, per observed enemy, the creature now standing for it (`None`: the
    /// simulator has no creature left for it). Pairing is by identity: the same monster id with the same alive state first, then the nearest HP
    /// (position only for an id the simulator never had). A random target (Lightning, Stampede) can kill a different enemy in the simulator than in the game; then the creature
    /// the game still shows alive is re-attached (the simulator's dead copy, HP set by the caller) and the one the game no longer lists is detached.
    /// No hooks fire (no death or spawn effects): like every sync, this aligns what the player sees.
    pub fn sync_enemies(&mut self, obs: &[ObsEnemy]) -> EnemySync {
        let mut rep = EnemySync::default();
        // every enemy-side monster ever spawned: the list first (in order), then the detached ones
        let mut pool: Vec<Cid> = self.enemies.iter().copied().collect();
        for c in 1..MAX_CREATURES as Cid {
            let cr = self.cr(c);
            if cr.active && cr.side == Side::Enemy && !cr.is_player && !cr.is_pet && !pool.contains(&c) {
                pool.push(c);
            }
        }
        let mut used = vec![false; pool.len()];
        for o in obs {
            let listed = |c: Cid| self.enemies.contains(c);
            let key = |j: usize| {
                let c = pool[j];
                let alive_now = listed(c) && self.cr(c).is_alive();
                ((alive_now != o.alive) as u8, !listed(c) as u8, (self.cr(c).hp - o.hp).abs(), j)
            };
            let pick = (0..pool.len()).filter(|&j| !used[j] && self.cr(pool[j]).monster.id == o.monster).min_by_key(|&j| key(j));
            if let Some(j) = pick {
                used[j] = true;
            }
            rep.pairs.push(pick.map(|j| pool[j]));
        }
        // an id the simulator never had (a spawn it resolved differently): the listed creature at that position stands in, as the old positional sync did
        let n_listed = self.enemies.len();
        for (k, p) in rep.pairs.iter_mut().enumerate() {
            if p.is_none() {
                rep.missing += 1;
                if let Some(j) = (k..n_listed).chain(0..k.min(n_listed)).find(|&j| !used[j]) {
                    used[j] = true;
                    *p = Some(pool[j]);
                }
            }
        }
        for (j, &c) in pool.iter().enumerate() {
            if !used[j] && self.enemies.contains(c) {
                self.detach_creature(c);
                if self.cr(c).is_alive() {
                    rep.removed += 1;
                }
            }
        }
        self.enemies.clear();
        for (o, c) in obs.iter().zip(rep.pairs.iter()) {
            let Some(c) = *c else { continue };
            let cr = self.cr_mut(c);
            if o.alive && (!cr.in_combat || cr.hp <= 0) {
                rep.revived += 1;
            }
            // a corpse the game still lists (Fabricator's bots) is listed for the comparison but stays out of the fight (no second death)
            cr.in_combat |= o.alive;
            cr.hp = o.hp;
            cr.max_hp = o.max_hp;
            cr.block = o.block;
            self.enemies.push(c);
        }
        rep
    }

    /// At a pending choose-a-card screen over generated cards (Attack / Skill / Power / Colorless Potion, Discovery), the simulator rolled its own
    /// offer. Makes the game's offer (`want`: (card id, upgrade) in the game's order) the candidates. False (nothing changed) when no such prompt is pending.
    pub fn sync_options(&mut self, want: &[(u16, u8)]) -> bool {
        if !matches!(self.decision, Some(Decision { source: DecisionSource::Options, .. })) || self.replay.is_some() {
            return false;
        }
        let mut cands: ArrayVec<CardIdx, MAX_CARDS> = ArrayVec::new();
        for &(id, up) in want {
            match self.new_card(id, up) {
                Some(c) => cands.push(c),
                None => return false,
            }
        }
        let d = self.decision.as_mut().expect("pending decision");
        d.cands = cands;
        d.selected.clear();
        true
    }
}

/// One enemy of the observation (the game's enemy list, in order).
#[derive(Clone, Copy, Debug)]
pub struct ObsEnemy {
    pub monster: u16,
    pub hp: i32,
    pub max_hp: i32,
    pub block: i32,
    pub alive: bool,
}

/// What `sync_enemies` did. `pairs[i]`: the creature for observed enemy i.
#[derive(Clone, Debug, Default)]
pub struct EnemySync {
    pub pairs: Vec<Option<Cid>>,
    /// Enemies the game shows alive that the simulator had killed (re-attached).
    pub revived: u16,
    /// Living simulated enemies the game does not list (detached).
    pub removed: u16,
    /// Observed enemies with no creature of that monster id (paired by position when a listed creature is left, else left out of the list).
    pub missing: u16,
}
