//! Status cards generated by Act 2 "Hive" monsters: Toxic (Myte). Stats come from gen_cards.rs.


// Toxic: cost 1, Exhaust, no OnPlay effect; at turn end in hand deals 5 Unpowered|Move damage to the owner
// (card source, no dealer).
// (Toxic lives in status.rs.)
