//! Status cards generated by Overgrowth monsters: Slimed, Infection, Dazed, Wound (stats from gen_cards.rs).
//! (If another branch also defines one of these, keep a single definition on merge.)

use crate::dec::Dec;
use crate::defs::*;
use crate::hooks::*;
use crate::listener;
use crate::state::*;
use crate::types::*;

// Slimed: cost 1, Exhaust; OnPlay draws `Cards` (1) card.
listener!(Slimed {
    fn on_play(&self, cx: &mut Combat, play: &CardPlay, _phase: u8) -> Flow {
        let n = cx.card_var(play.card, VarKind::Cards);
        cx.draw_cards(n, false);
        Flow::Done
    }
});

// Infection: unplayable; at turn end in hand deals 3 Unpowered|Move damage to the owner (no dealer, card source).
listener!(Infection {
    fn on_turn_end_in_hand(&self, cx: &mut Combat, card: CardIdx) {
        let n = cx.card_var(card, VarKind::Damage);
        cx.damage(&[PLAYER], Dec::int(n as i64), ValueProp::UNPOWERED.or(ValueProp::MOVE), NO, card);
    }
});

listener!(Dazed {});
listener!(Wound {});
