//! Status cards generated by the Act 3 Glory elites / bosses (slice glory-b): Burn, Wither.
//! (If another branch also defines one of these, keep a single definition on merge.)

use crate::dec::Dec;
use crate::defs::VarKind;
use crate::listener;
use crate::state::*;
use crate::types::*;

// Burn: unplayable; at turn end in hand deals 2 Unpowered|Move damage to the owner (no dealer, card source).
listener!(Burn {
    fn on_turn_end_in_hand(&self, cx: &mut Combat, card: CardIdx) {
        let n = cx.card_var(card, VarKind::Damage);
        cx.damage(&[PLAYER], Dec::int(n as i64), ValueProp::UNPOWERED.or(ValueProp::MOVE), NO, card);
    }
});

// Wither: like Burn with Damage 3; Aeonglass "fake upgrades" it (`Damage += 3` per level via `Card::dmg_bonus`).
listener!(Wither {
    fn on_turn_end_in_hand(&self, cx: &mut Combat, card: CardIdx) {
        let n = cx.card_var(card, VarKind::Damage);
        cx.damage(&[PLAYER], Dec::int(n as i64), ValueProp::UNPOWERED.or(ValueProp::MOVE), NO, card);
    }
});
