//! Status cards generated by Act 1b monsters (HauntedShip: Dazed; SoulFysh: Beckon).

use crate::dec::Dec;
use crate::defs::VarKind;
use crate::listener;
use crate::state::*;
use crate::types::*;

// Dazed: Ethereal + Unplayable status; no logic (generic Ethereal exhaust at turn end).
listener!(Dazed {});

// Beckon (cost 1 status): at the end of the owner's turn, while in hand, loses 6 HP (unblockable, unpowered).
listener!(Beckon {
    fn on_turn_end_in_hand(&self, cx: &mut Combat, card: CardIdx) {
        let loss = cx.card_var(card, VarKind::HpLoss);
        cx.damage(&[PLAYER], Dec::int(loss as i64), ValueProp::UNBLOCKABLE.or(ValueProp::UNPOWERED).or(ValueProp::MOVE), PLAYER, card);
    }
});
