// @generated by scripts/porting/gen_relics.py from the decompiled game source. Do not edit.
#![allow(dead_code)]
use crate::dec::Dec;

pub mod akabeko {
    #[allow(unused_imports)]
    use super::*;
    pub const VIGOR_POWER: i32 = 8;
}
pub mod alchemical_coffer {
    #[allow(unused_imports)]
    use super::*;
    pub const POTION_SLOTS: i32 = 4;
}
pub mod amethyst_aubergine {
    #[allow(unused_imports)]
    use super::*;
    pub const GOLD: i32 = 15;
}
pub mod anchor {
    #[allow(unused_imports)]
    use super::*;
    pub const BLOCK: i32 = 10;
}
pub mod arcane_scroll {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 1;
}
pub mod art_of_war {
    #[allow(unused_imports)]
    use super::*;
    pub const ENERGY: i32 = 1;
}
pub mod astrolabe {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 3;
}
pub mod bag_of_marbles {
    #[allow(unused_imports)]
    use super::*;
    pub const VULNERABLE_POWER: i32 = 1;
}
pub mod bag_of_preparation {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 2;
}
pub mod beating_remnant {
    #[allow(unused_imports)]
    use super::*;
    pub const MAX_HP_LOSS: i32 = 20;
}
pub mod beautiful_bracelet {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 4;
    pub const SWIFT: i32 = 2;
}
pub mod belt_buckle {
    #[allow(unused_imports)]
    use super::*;
    pub const DEXTERITY_POWER: i32 = 2;
}
pub mod big_hat {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 2;
}
pub mod big_mushroom {
    #[allow(unused_imports)]
    use super::*;
    pub const MAX_HP: i32 = 20;
    pub const CARDS: i32 = 2;
}
pub mod biiig_hug {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 4;
}
pub mod black_blood {
    #[allow(unused_imports)]
    use super::*;
    pub const HEAL: i32 = 12;
}
pub mod blessed_antler {
    #[allow(unused_imports)]
    use super::*;
    pub const ENERGY: i32 = 1;
    pub const CARDS: i32 = 3;
}
pub mod blood_soaked_rose {
    #[allow(unused_imports)]
    use super::*;
    pub const ENERGY: i32 = 1;
}
pub mod blood_vial {
    #[allow(unused_imports)]
    use super::*;
    pub const HEAL: i32 = 2;
}
pub mod bone_flute {
    #[allow(unused_imports)]
    use super::*;
    pub const BLOCK: i32 = 2;
}
pub mod book_of_five_rings {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 5;
    pub const HEAL: i32 = 20;
}
pub mod book_repair_knife {
    #[allow(unused_imports)]
    use super::*;
    pub const HEAL: i32 = 3;
}
pub mod booming_conch {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 2;
    pub const ENERGY: i32 = 1;
}
pub mod bound_phylactery {
    #[allow(unused_imports)]
    use super::*;
    pub const SUMMON: i32 = 1;
}
pub mod bowler_hat {
    #[allow(unused_imports)]
    use super::*;
    pub const GOLD_INCREASE: Dec = Dec::frac(125, 2);
}
pub mod bread {
    #[allow(unused_imports)]
    use super::*;
    pub const GAIN_ENERGY: i32 = 1;
    pub const LOSE_ENERGY: i32 = 2;
}
pub mod brilliant_scarf {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 5;
}
pub mod brimstone {
    #[allow(unused_imports)]
    use super::*;
    pub const SELF_STRENGTH: i32 = 2;
    pub const ENEMY_STRENGTH: i32 = 1;
}
pub mod bronze_scales {
    #[allow(unused_imports)]
    use super::*;
    pub const THORNS_POWER: i32 = 3;
}
pub mod burning_blood {
    #[allow(unused_imports)]
    use super::*;
    pub const HEAL: i32 = 6;
}
pub mod calling_bell {
    #[allow(unused_imports)]
    use super::*;
    pub const RELICS: i32 = 3;
}
pub mod candelabra {
    #[allow(unused_imports)]
    use super::*;
    pub const ENERGY: i32 = 2;
}
pub mod captains_wheel {
    #[allow(unused_imports)]
    use super::*;
    pub const BLOCK: i32 = 18;
}
pub mod cauldron {
    #[allow(unused_imports)]
    use super::*;
    pub const POTIONS: i32 = 5;
}
pub mod centennial_puzzle {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 3;
}
pub mod chandelier {
    #[allow(unused_imports)]
    use super::*;
    pub const ENERGY: i32 = 3;
}
pub mod charons_ashes {
    #[allow(unused_imports)]
    use super::*;
    pub const DAMAGE: i32 = 3;
}
pub mod chemical_x {
    #[allow(unused_imports)]
    use super::*;
    pub const INCREASE: i32 = 2;
}
pub mod choices_paradox {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 5;
}
pub mod chosen_cheese {
    #[allow(unused_imports)]
    use super::*;
    pub const MAX_HP: i32 = 1;
}
pub mod claws {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 6;
}
pub mod cloak_clasp {
    #[allow(unused_imports)]
    use super::*;
    pub const BLOCK: i32 = 1;
}
pub mod cracked_core {
    #[allow(unused_imports)]
    use super::*;
    pub const LIGHTNING: i32 = 1;
}
pub mod cursed_pearl {
    #[allow(unused_imports)]
    use super::*;
    pub const GOLD: i32 = 333;
}
pub mod darkstone_periapt {
    #[allow(unused_imports)]
    use super::*;
    pub const MAX_HP: i32 = 6;
}
pub mod data_disk {
    #[allow(unused_imports)]
    use super::*;
    pub const FOCUS_POWER: i32 = 1;
}
pub mod daughter_of_the_wind {
    #[allow(unused_imports)]
    use super::*;
    pub const BLOCK: i32 = 1;
}
pub mod diamond_diadem {
    #[allow(unused_imports)]
    use super::*;
    pub const BLOCK: i32 = 20;
}
pub mod distinguished_cape {
    #[allow(unused_imports)]
    use super::*;
    pub const CURSES: i32 = 2;
    pub const CARDS: i32 = 3;
}
pub mod divine_destiny {
    #[allow(unused_imports)]
    use super::*;
    pub const STARS: i32 = 7;
}
pub mod divine_right {
    #[allow(unused_imports)]
    use super::*;
    pub const STARS: i32 = 3;
}
pub mod dragon_fruit {
    #[allow(unused_imports)]
    use super::*;
    pub const MAX_HP: i32 = 1;
}
pub mod ectoplasm {
    #[allow(unused_imports)]
    use super::*;
    pub const ENERGY: i32 = 1;
}
pub mod ember_tea {
    #[allow(unused_imports)]
    use super::*;
    pub const STRENGTH_POWER: i32 = 2;
}
pub mod empty_cage {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 2;
}
pub mod eternal_feather {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 5;
    pub const HEAL: i32 = 3;
}
pub mod fake_anchor {
    #[allow(unused_imports)]
    use super::*;
    pub const BLOCK: i32 = 4;
}
pub mod fake_blood_vial {
    #[allow(unused_imports)]
    use super::*;
    pub const HEAL: i32 = 1;
}
pub mod fake_happy_flower {
    #[allow(unused_imports)]
    use super::*;
    pub const ENERGY: i32 = 1;
    pub const TURNS: i32 = 5;
}
pub mod fake_lees_waffle {
    #[allow(unused_imports)]
    use super::*;
    pub const HEAL: i32 = 10;
}
pub mod fake_mango {
    #[allow(unused_imports)]
    use super::*;
    pub const MAX_HP: i32 = 3;
}
pub mod fake_orichalcum {
    #[allow(unused_imports)]
    use super::*;
    pub const BLOCK: i32 = 3;
}
pub mod fake_strike_dummy {
    #[allow(unused_imports)]
    use super::*;
    pub const EXTRA_DAMAGE: i32 = 1;
}
pub mod fake_venerable_tea_set {
    #[allow(unused_imports)]
    use super::*;
    pub const ENERGY: i32 = 1;
}
pub mod fencing_manual {
    #[allow(unused_imports)]
    use super::*;
    pub const FORGE: i32 = 10;
}
pub mod festive_popper {
    #[allow(unused_imports)]
    use super::*;
    pub const DAMAGE: i32 = 9;
}
pub mod fiddle {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 2;
}
pub mod fishing_rod {
    #[allow(unused_imports)]
    use super::*;
    pub const COMBATS: i32 = 3;
}
pub mod forgotten_soul {
    #[allow(unused_imports)]
    use super::*;
    pub const DAMAGE: i32 = 1;
}
pub mod fragrant_mushroom {
    #[allow(unused_imports)]
    use super::*;
    pub const HP_LOSS: i32 = 15;
    pub const CARDS: i32 = 2;
}
pub mod fresnel_lens {
    #[allow(unused_imports)]
    use super::*;
    pub const NIMBLE_AMOUNT: i32 = 2;
}
pub mod funerary_mask {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 3;
}
pub mod fur_coat {
    #[allow(unused_imports)]
    use super::*;
    pub const COMBATS: i32 = 8;
}
pub mod galactic_dust {
    #[allow(unused_imports)]
    use super::*;
    pub const STARS: i32 = 10;
    pub const BLOCK: i32 = 10;
}
pub mod game_piece {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 1;
}
pub mod gnarled_hammer {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 3;
    pub const SHARP_AMOUNT: i32 = 3;
}
pub mod golden_pearl {
    #[allow(unused_imports)]
    use super::*;
    pub const GOLD: i32 = 150;
}
pub mod gorget {
    #[allow(unused_imports)]
    use super::*;
    pub const PLATING_POWER: i32 = 4;
}
pub mod gremlin_horn {
    #[allow(unused_imports)]
    use super::*;
    pub const ENERGY: i32 = 1;
    pub const CARDS: i32 = 1;
}
pub mod hand_drill {
    #[allow(unused_imports)]
    use super::*;
    pub const VULNERABLE_POWER: i32 = 2;
}
pub mod happy_flower {
    #[allow(unused_imports)]
    use super::*;
    pub const ENERGY: i32 = 1;
    pub const TURNS: i32 = 3;
}
pub mod hefty_tablet {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 3;
}
pub mod helical_dart {
    #[allow(unused_imports)]
    use super::*;
    pub const DEXTERITY_POWER: i32 = 1;
}
pub mod horn_cleat {
    #[allow(unused_imports)]
    use super::*;
    pub const BLOCK: i32 = 14;
}
pub mod infused_core {
    #[allow(unused_imports)]
    use super::*;
    pub const LIGHTNING: i32 = 3;
    pub const EXTRA_DAMAGE: i32 = 1;
}
pub mod intimidating_helmet {
    #[allow(unused_imports)]
    use super::*;
    pub const BLOCK: i32 = 4;
    pub const ENERGY: i32 = 2;
}
pub mod iron_club {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 4;
}
pub mod ivory_tile {
    #[allow(unused_imports)]
    use super::*;
    pub const ENERGY: i32 = 1;
    pub const ENERGY_THRESHOLD: i32 = 3;
}
pub mod joss_paper {
    #[allow(unused_imports)]
    use super::*;
    pub const EXHAUST_AMOUNT: i32 = 5;
    pub const CARDS: i32 = 1;
}
pub mod kaleidoscope {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 2;
}
pub mod kifuda {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 3;
}
pub mod kunai {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 3;
    pub const DEXTERITY_POWER: i32 = 1;
}
pub mod kusarigama {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 3;
    pub const DAMAGE: i32 = 6;
}
pub mod lantern {
    #[allow(unused_imports)]
    use super::*;
    pub const ENERGY: i32 = 1;
}
pub mod lava_rock {
    #[allow(unused_imports)]
    use super::*;
    pub const RELICS: i32 = 2;
}
pub mod leafy_poultice {
    #[allow(unused_imports)]
    use super::*;
    pub const MAX_HP: i32 = 12;
}
pub mod lees_waffle {
    #[allow(unused_imports)]
    use super::*;
    pub const MAX_HP: i32 = 7;
}
pub mod letter_opener {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 3;
    pub const DAMAGE: i32 = 5;
}
pub mod lizard_tail {
    #[allow(unused_imports)]
    use super::*;
    pub const HEAL: i32 = 50;
}
pub mod looming_fruit {
    #[allow(unused_imports)]
    use super::*;
    pub const MAX_HP: i32 = 31;
}
pub mod lost_wisp {
    #[allow(unused_imports)]
    use super::*;
    pub const DAMAGE: i32 = 8;
}
pub mod lucky_fysh {
    #[allow(unused_imports)]
    use super::*;
    pub const GOLD: i32 = 15;
}
pub mod lunar_pastry {
    #[allow(unused_imports)]
    use super::*;
    pub const STARS: i32 = 1;
}
pub mod mango {
    #[allow(unused_imports)]
    use super::*;
    pub const MAX_HP: i32 = 14;
}
pub mod maw_bank {
    #[allow(unused_imports)]
    use super::*;
    pub const GOLD: i32 = 12;
}
pub mod meal_ticket {
    #[allow(unused_imports)]
    use super::*;
    pub const HEAL: i32 = 15;
}
pub mod meat_on_the_bone {
    #[allow(unused_imports)]
    use super::*;
    pub const HP_THRESHOLD: i32 = 50;
    pub const HEAL: i32 = 12;
}
pub mod membership_card {
    #[allow(unused_imports)]
    use super::*;
    pub const DISCOUNT: i32 = 50;
}
pub mod mercury_hourglass {
    #[allow(unused_imports)]
    use super::*;
    pub const DAMAGE: i32 = 3;
}
pub mod metronome {
    #[allow(unused_imports)]
    use super::*;
    pub const DAMAGE: i32 = 30;
    pub const ORB_COUNT: i32 = 7;
}
pub mod mini_regent {
    #[allow(unused_imports)]
    use super::*;
    pub const STRENGTH_POWER: i32 = 1;
}
pub mod miniature_cannon {
    #[allow(unused_imports)]
    use super::*;
    pub const EXTRA_DAMAGE: i32 = 3;
}
pub mod mystic_lighter {
    #[allow(unused_imports)]
    use super::*;
    pub const DAMAGE: i32 = 9;
}
pub mod neows_bones {
    #[allow(unused_imports)]
    use super::*;
    pub const RELICS: i32 = 2;
    pub const CURSES: i32 = 1;
}
pub mod new_leaf {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 1;
}
pub mod ninja_scroll {
    #[allow(unused_imports)]
    use super::*;
    pub const SHIVS: i32 = 3;
}
pub mod nunchaku {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 10;
    pub const ENERGY: i32 = 1;
}
pub mod nutritious_oyster {
    #[allow(unused_imports)]
    use super::*;
    pub const MAX_HP: i32 = 11;
}
pub mod oddly_smooth_stone {
    #[allow(unused_imports)]
    use super::*;
    pub const DEXTERITY_POWER: i32 = 1;
}
pub mod old_coin {
    #[allow(unused_imports)]
    use super::*;
    pub const GOLD: i32 = 300;
}
pub mod orange_dough {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 2;
}
pub mod orichalcum {
    #[allow(unused_imports)]
    use super::*;
    pub const BLOCK: i32 = 6;
}
pub mod ornamental_fan {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 3;
    pub const BLOCK: i32 = 4;
}
pub mod orrery {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 5;
}
pub mod paels_blood {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 1;
}
pub mod paels_claw {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 3;
}
pub mod paels_flesh {
    #[allow(unused_imports)]
    use super::*;
    pub const ENERGY: i32 = 1;
}
pub mod paels_legion {
    #[allow(unused_imports)]
    use super::*;
    pub const TURNS: i32 = 2;
}
pub mod paels_tears {
    #[allow(unused_imports)]
    use super::*;
    pub const ENERGY: i32 = 2;
}
pub mod paels_tooth {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 5;
}
pub mod paels_wing {
    #[allow(unused_imports)]
    use super::*;
    pub const SACRIFICES: i32 = 2;
}
pub mod pantograph {
    #[allow(unused_imports)]
    use super::*;
    pub const HEAL: i32 = 25;
}
pub mod parrying_shield {
    #[allow(unused_imports)]
    use super::*;
    pub const BLOCK: i32 = 10;
    pub const DAMAGE: i32 = 6;
}
pub mod pear {
    #[allow(unused_imports)]
    use super::*;
    pub const MAX_HP: i32 = 10;
}
pub mod pendulum {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 1;
    pub const TURNS: i32 = 3;
}
pub mod permafrost {
    #[allow(unused_imports)]
    use super::*;
    pub const BLOCK: i32 = 7;
}
pub mod phial_holster {
    #[allow(unused_imports)]
    use super::*;
    pub const POTION_SLOTS: i32 = 1;
    pub const POTIONS: i32 = 2;
}
pub mod philosophers_stone {
    #[allow(unused_imports)]
    use super::*;
    pub const STRENGTH_POWER: i32 = 1;
    pub const ENERGY: i32 = 1;
}
pub mod phylactery_unbound {
    #[allow(unused_imports)]
    use super::*;
    pub const START_OF_COMBAT: i32 = 5;
    pub const START_OF_TURN: i32 = 2;
}
pub mod planisphere {
    #[allow(unused_imports)]
    use super::*;
    pub const HEAL: i32 = 5;
}
pub mod pocketwatch {
    #[allow(unused_imports)]
    use super::*;
    pub const CARD_THRESHOLD: i32 = 3;
    pub const CARDS: i32 = 3;
}
pub mod pollinous_core {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 2;
    pub const TURNS: i32 = 4;
}
pub mod pomander {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 1;
}
pub mod potion_belt {
    #[allow(unused_imports)]
    use super::*;
    pub const POTION_SLOTS: i32 = 2;
}
pub mod power_cell {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 2;
}
pub mod precarious_shears {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 2;
    pub const DAMAGE: i32 = 16;
}
pub mod precise_scissors {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 1;
}
pub mod preserved_fog {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 3;
}
pub mod prismatic_gem {
    #[allow(unused_imports)]
    use super::*;
    pub const ENERGY: i32 = 1;
}
pub mod pumpkin_candle {
    #[allow(unused_imports)]
    use super::*;
    pub const COMBAT_COUNT: i32 = 5;
    pub const ENERGY: i32 = 1;
}
pub mod punch_dagger {
    #[allow(unused_imports)]
    use super::*;
    pub const MOMENTUM: i32 = 5;
}
pub mod radiant_pearl {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 1;
}
pub mod rainbow_ring {
    #[allow(unused_imports)]
    use super::*;
    pub const STRENGTH_POWER: i32 = 1;
    pub const DEXTERITY_POWER: i32 = 1;
}
pub mod red_mask {
    #[allow(unused_imports)]
    use super::*;
    pub const WEAK_POWER: i32 = 1;
}
pub mod red_skull {
    #[allow(unused_imports)]
    use super::*;
    pub const HP_THRESHOLD: i32 = 50;
    pub const STRENGTH_POWER: i32 = 3;
}
pub mod regal_pillow {
    #[allow(unused_imports)]
    use super::*;
    pub const HEAL: i32 = 15;
}
pub mod regalite {
    #[allow(unused_imports)]
    use super::*;
    pub const BLOCK: i32 = 4;
}
pub mod reptile_trinket {
    #[allow(unused_imports)]
    use super::*;
    pub const STRENGTH_POWER: i32 = 3;
}
pub mod ring_of_the_drake {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 2;
    pub const TURNS: i32 = 3;
}
pub mod ring_of_the_snake {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 2;
}
pub mod ripple_basin {
    #[allow(unused_imports)]
    use super::*;
    pub const BLOCK: i32 = 4;
}
pub mod royal_poison {
    #[allow(unused_imports)]
    use super::*;
    pub const DAMAGE: i32 = 4;
}
pub mod royal_stamp {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 1;
}
pub mod runic_capacitor {
    #[allow(unused_imports)]
    use super::*;
    pub const REPEAT: i32 = 3;
}
pub mod sai {
    #[allow(unused_imports)]
    use super::*;
    pub const BLOCK: i32 = 7;
}
pub mod sand_castle {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 6;
}
pub mod screaming_flagon {
    #[allow(unused_imports)]
    use super::*;
    pub const DAMAGE: i32 = 20;
}
pub mod sea_glass {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 15;
}
pub mod seal_of_gold {
    #[allow(unused_imports)]
    use super::*;
    pub const ENERGY: i32 = 1;
    pub const GOLD: i32 = 3;
}
pub mod self_forming_clay {
    #[allow(unused_imports)]
    use super::*;
    pub const BLOCK_NEXT_TURN: i32 = 3;
}
pub mod sere_talon {
    #[allow(unused_imports)]
    use super::*;
    pub const HP_LOSS: i32 = 9;
    pub const WISHES: i32 = 3;
}
pub mod shuriken {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 3;
    pub const STRENGTH_POWER: i32 = 1;
}
pub mod signet_ring {
    #[allow(unused_imports)]
    use super::*;
    pub const GOLD: i32 = 888;
}
pub mod silver_crucible {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 3;
}
pub mod sling_of_courage {
    #[allow(unused_imports)]
    use super::*;
    pub const STRENGTH_POWER: i32 = 2;
}
pub mod snecko_eye {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 2;
}
pub mod snecko_skull {
    #[allow(unused_imports)]
    use super::*;
    pub const POISON_POWER: i32 = 1;
}
pub mod sozu {
    #[allow(unused_imports)]
    use super::*;
    pub const ENERGY: i32 = 1;
}
pub mod sparkling_rouge {
    #[allow(unused_imports)]
    use super::*;
    pub const STRENGTH_POWER: i32 = 1;
    pub const DEXTERITY_POWER: i32 = 1;
}
pub mod spiked_gauntlets {
    #[allow(unused_imports)]
    use super::*;
    pub const ENERGY: i32 = 1;
}
pub mod stone_calendar {
    #[allow(unused_imports)]
    use super::*;
    pub const DAMAGE: i32 = 52;
    pub const DAMAGE_TURN: i32 = 7;
}
pub mod stone_cracker {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 2;
}
pub mod stone_humidifier {
    #[allow(unused_imports)]
    use super::*;
    pub const MAX_HP: i32 = 5;
}
pub mod strawberry {
    #[allow(unused_imports)]
    use super::*;
    pub const MAX_HP: i32 = 7;
}
pub mod strike_dummy {
    #[allow(unused_imports)]
    use super::*;
    pub const EXTRA_DAMAGE: i32 = 3;
}
pub mod sturdy_clamp {
    #[allow(unused_imports)]
    use super::*;
    pub const BLOCK: i32 = 10;
}
pub mod sword_of_jade {
    #[allow(unused_imports)]
    use super::*;
    pub const STRENGTH_POWER: i32 = 3;
}
pub mod sword_of_stone {
    #[allow(unused_imports)]
    use super::*;
    pub const ELITES: i32 = 5;
}
pub mod symbiotic_virus {
    #[allow(unused_imports)]
    use super::*;
    pub const DARK: i32 = 1;
}
pub mod tea_of_discourtesy {
    #[allow(unused_imports)]
    use super::*;
    pub const HEAL: i32 = 1;
    pub const DAZED_COUNT: i32 = 2;
}
pub mod the_abacus {
    #[allow(unused_imports)]
    use super::*;
    pub const BLOCK: i32 = 6;
}
pub mod the_boot {
    #[allow(unused_imports)]
    use super::*;
    pub const DAMAGE_MINIMUM: i32 = 5;
    pub const DAMAGE_THRESHOLD: i32 = 4;
}
pub mod the_courier {
    #[allow(unused_imports)]
    use super::*;
    pub const DISCOUNT: i32 = 20;
}
pub mod tingsha {
    #[allow(unused_imports)]
    use super::*;
    pub const DAMAGE: i32 = 3;
}
pub mod toasty_mittens {
    #[allow(unused_imports)]
    use super::*;
    pub const STRENGTH_POWER: i32 = 1;
}
pub mod toolbox {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 3;
}
pub mod tough_bandages {
    #[allow(unused_imports)]
    use super::*;
    pub const BLOCK: i32 = 3;
}
pub mod toy_box {
    #[allow(unused_imports)]
    use super::*;
    pub const RELICS: i32 = 5;
    pub const COMBATS: i32 = 3;
}
pub mod tri_boomerang {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 3;
}
pub mod tungsten_rod {
    #[allow(unused_imports)]
    use super::*;
    pub const HP_LOSS_REDUCTION: i32 = 1;
}
pub mod tuning_fork {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 10;
    pub const BLOCK: i32 = 7;
}
pub mod twisted_funnel {
    #[allow(unused_imports)]
    use super::*;
    pub const POISON_POWER: i32 = 4;
}
pub mod undying_sigil {
    #[allow(unused_imports)]
    use super::*;
    pub const DAMAGE_DECREASE: Dec = Dec::frac(5, 1);
}
pub mod vajra {
    #[allow(unused_imports)]
    use super::*;
    pub const STRENGTH_POWER: i32 = 1;
}
pub mod velvet_choker {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 6;
    pub const ENERGY: i32 = 1;
}
pub mod venerable_tea_set {
    #[allow(unused_imports)]
    use super::*;
    pub const ENERGY: i32 = 2;
}
pub mod very_hot_cocoa {
    #[allow(unused_imports)]
    use super::*;
    pub const ENERGY: i32 = 4;
}
pub mod war_hammer {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 4;
}
pub mod war_paint {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 2;
}
pub mod whetstone {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 2;
}
pub mod whispering_earring {
    #[allow(unused_imports)]
    use super::*;
    pub const ENERGY: i32 = 1;
}
pub mod wing_charm {
    #[allow(unused_imports)]
    use super::*;
    pub const SWIFT_AMOUNT: i32 = 1;
}
pub mod winged_boots {
    #[allow(unused_imports)]
    use super::*;
    pub const ROOMS: i32 = 3;
}
pub mod wongos_mystery_ticket {
    #[allow(unused_imports)]
    use super::*;
    pub const REPEAT: i32 = 3;
    pub const REMAINING_COMBATS: i32 = 5;
}
pub mod yummy_cookie {
    #[allow(unused_imports)]
    use super::*;
    pub const CARDS: i32 = 4;
}
