//! Game content: one Rust type per card / power / relic / monster, registered by id.
//!
//! Adding content = write a `listener!` (plus a def) and add one line to the registry below. Anything not
//! registered is treated as "unimplemented": `Scenario` validation rejects it, so a fight can never silently
//! run with a missing rule.

pub mod gen_cards;
pub mod gen_pools;
pub mod gen_potions;
pub mod gen_relics;
pub mod gen_powers;

use crate::defs::*;
use crate::hooks::*;
use crate::ids;

/// Listener with no overridden hooks (unregistered / hook-less content).
pub struct NoListener;
impl Listener for NoListener {}
static NO_LISTENER: NoListener = NoListener;

macro_rules! registry {
    ($lfn:ident, $mfn:ident, $ids:ident, $default:expr; $($id:ident => $ty:path),* $(,)?) => {
        #[inline]
        pub fn $lfn(id: u16) -> &'static dyn Listener {
            match id { $( ids::$ids::$id => &$ty, )* _ => $default }
        }
        #[inline]
        pub fn $mfn(id: u16) -> Mask {
            match id { $( ids::$ids::$id => <$ty as HasMask>::MASK, )* _ => Mask::EMPTY }
        }
    };
    (impl $ifn:ident, $ids:ident; $($id:ident => $ty:path),* $(,)?) => {
        pub fn $ifn(id: u16) -> bool {
            // (robust for an empty list: a category with nothing ported yet)
            $( if id == ids::$ids::$id { return true; } )*
            let _ = id;
            false
        }
    };
}

/// Dispatch a hook to the listener identified by `me`.
#[inline]
pub fn listener(me: &Me) -> &'static dyn Listener {
    match me.kind {
        Kind::Power => power_listener(me.id),
        Kind::Relic => relic_listener(me.id),
        Kind::Potion => potion_listener(me.id),
        Kind::Card => card_listener(me.id),
        Kind::Monster => monster_listener(me.id),
        Kind::Enchantment => enchantment_listener(me.id),
        Kind::Affliction => affliction_listener(me.id),
        Kind::Orb => &NO_LISTENER,
    }
}

#[inline(always)]
pub fn card_def(id: u16) -> &'static CardDef {
    &gen_cards::CARD_DEFS[id as usize]
}

#[inline(always)]
pub fn potion_def(id: u16) -> &'static PotionDef {
    &gen_potions::POTION_DEFS[id as usize]
}

#[inline(always)]
pub fn power_def(id: u16) -> &'static PowerDef {
    &gen_powers::POWER_DEFS[id as usize]
}

/// One monster spawned by an encounter, in creation order: `(monster, slot index or NO, private vars)`.
#[derive(Clone, Copy)]
pub struct Spawn {
    pub monster: u16,
    pub slot: u8,
    pub vars: [i32; 2],
}
pub type Spawns = crate::util::ArrayVec<Spawn, 16>;

// Everything below is generated by build.rs from the files under src/content/*/.
include!(concat!(env!("OUT_DIR"), "/registry.rs"));

pub fn relic_def_exists(_id: u16) -> bool {
    true
}

/// Node index of a move/branch of `monster`'s state machine by its id string (e.g. `"REVIVE_MOVE"`).
pub fn node_by_name(monster: u16, name: &str) -> Option<u8> {
    let def = monster_def(monster);
    def.nodes.iter().position(|n| match n {
        MonsterNode::Move { id, .. } | MonsterNode::Random { id, .. } | MonsterNode::Cond { id, .. } => *id == name,
    }).map(|i| i as u8)
}
