using Sts2Solver.Engine;

namespace Sts2Solver.Content;

/// <summary>Status card (unplayable). At end of the player's turn, every copy held in hand deals 3
/// damage to the player — unpowered (no Strength/Vulnerable) but blockable. Added to the discard pile
/// by Phrog Parasite's Infect and Wriggler's Wriggle. (MegaCrit Infection)</summary>
public sealed class Infection : CardModel
{
    public override string Name => "Infection";
    public override int BaseCost => -1;                 // unplayable; cost is irrelevant
    public override CardType Type => CardType.Status;
    public override CardRarity Rarity => CardRarity.Status;
    public override TargetType Target => TargetType.None;

    public override bool Unplayable => true;
    public override bool HasTurnEndInHandEffect => true;

    public int Damage => 3;

    public override void OnPlay(CombatState combat, CardPlay play) { }  // never played

    public override void OnTurnEndInHand(CombatState combat)
        => Cmd.Attack(combat, combat.Player, combat.Player, Damage, ValueProp.Unpowered | ValueProp.Move, this);
}
/// <summary>Status card (unplayable). At end of the player's turn, every copy held in hand deals 2
/// damage to the player — unpowered but blockable. MechaKnight's Flamethrower adds 4 to the hand.
/// (MegaCrit Burn)</summary>
public sealed class Burn : CardModel
{
    public override string Name => "Burn";
    public override int BaseCost => -1;                 // unplayable
    public override CardType Type => CardType.Status;
    public override CardRarity Rarity => CardRarity.Status;
    public override TargetType Target => TargetType.None;

    public override bool Unplayable => true;
    public override bool HasTurnEndInHandEffect => true;

    public int Damage => 2;

    public override void OnPlay(CombatState combat, CardPlay play) { }  // never played

    public override void OnTurnEndInHand(CombatState combat)
        => Cmd.Attack(combat, combat.Player, combat.Player, Damage, ValueProp.Unpowered | ValueProp.Move, this);
}
/// <summary>Status card: Unplayable + Ethereal (exhausts at end of turn if still in hand). No effect
/// while held — pure draw dilution. Shuffled into the draw pile by Entomancer's Personal Hive.
/// (MegaCrit Dazed)</summary>
public sealed class Dazed : CardModel
{
    public override string Name => "Dazed";
    public override int BaseCost => -1;
    public override CardType Type => CardType.Status;
    public override CardRarity Rarity => CardRarity.Status;
    public override TargetType Target => TargetType.None;

    public override bool Unplayable => true;
    public override bool Ethereal => true;

    public override void OnPlay(CombatState combat, CardPlay play) { }  // never played
}

/// <summary>Status card (unplayable). No effect while held — pure draw dilution. Generated by the Defect's
/// FightThrough (2 to discard). (MegaCrit Wound)</summary>
public sealed class Wound : CardModel
{
    public override string Name => "Wound";
    public override int BaseCost => -1;
    public override CardType Type => CardType.Status;
    public override CardRarity Rarity => CardRarity.Status;
    public override TargetType Target => TargetType.None;
    public override bool Unplayable => true;
    public override void OnPlay(CombatState combat, CardPlay play) { }
}

/// <summary>Status card: cost 1, Exhaust, draw 1 when played. Generated by the Defect's GunkUp (to discard).
/// (MegaCrit Slimed)</summary>
public sealed class Slimed : CardModel
{
    public override string Name => "Slimed";
    public override int BaseCost => 1;
    public override CardType Type => CardType.Status;
    public override CardRarity Rarity => CardRarity.Status;
    public override TargetType Target => TargetType.Self;
    public override CardResultPile ResultPile => CardResultPile.Exhaust;
    public override void OnPlay(CombatState combat, CardPlay play) => Cmd.Draw(combat, 1);
}

/// <summary>Status card: Unplayable + Ethereal. When drawn, lose 1 energy (the on-draw energy loss is a
/// documented unmodelled minor effect — it only arises from the Defect's Turbo, and modelling it would need a
/// per-card draw hook on the deferred-draw path; omitting it is the only mildly-optimistic gap in the Defect
/// port, of magnitude ≤1 energy). Models the dilution + end-of-turn exhaust faithfully. (MegaCrit Void)</summary>
public sealed class Void : CardModel
{
    public override string Name => "Void";
    public override int BaseCost => -1;
    public override CardType Type => CardType.Status;
    public override CardRarity Rarity => CardRarity.Status;
    public override TargetType Target => TargetType.None;
    public override bool Unplayable => true;
    public override bool Ethereal => true;
    public override void OnPlay(CombatState combat, CardPlay play) { }
}

/// <summary>Token card: cost 0, Exhaust, gain 1 energy + draw 1 when played. The Defect's Compact transforms
/// in-hand Status cards into Fuel. Upgrade: draw 2. (MegaCrit Fuel)</summary>
public sealed class Fuel : CardModel
{
    public override string Name => "Fuel";
    public override int BaseCost => 0;
    public override CardType Type => CardType.Skill;
    public override CardRarity Rarity => CardRarity.Token;
    public override TargetType Target => TargetType.Self;
    public override CardResultPile ResultPile => CardResultPile.Exhaust;
    public int Cards => 1 + Upgrades;
    public override void OnPlay(CombatState combat, CardPlay play)
    {
        Cmd.GainEnergy(combat, 1);
        Cmd.Draw(combat, Cards);
    }
}

/// <summary>Curse: Unplayable + Ethereal (exhausts at end of turn if still in hand) + Eternal (can't be
/// removed from the deck between combats). The starting curse added to every deck at Ascension 5+
/// (AscendersBane), so it appears in the opening hand/draw of every A10 run. No combat effect — pure draw
/// dilution. (MegaCrit AscendersBane)</summary>
public sealed class AscendersBane : CardModel
{
    public override string Name => "AscendersBane";
    public override int BaseCost => -1;
    public override CardType Type => CardType.Curse;
    public override CardRarity Rarity => CardRarity.Curse;
    public override TargetType Target => TargetType.None;

    public override bool Unplayable => true;
    public override bool Ethereal => true;

    public override void OnPlay(CombatState combat, CardPlay play) { }  // never played
}
