#!/usr/bin/env python3
"""Generates `crates/sts2sim/src/relic_mask.rs` from `data/relic_classes.json` (`docs/rl_redesign.md` M2): which relics the network observes.

A relic is observed when it acts in combat (class `combat`, or `combat` among its secondary classes); macro-only relics and potion / card-linked relics
without a combat effect of their own are left out of the observation (their effect, if any, is the potions or cards the scenario carries).

  python tools/gen_relic_mask.py        # rewrite the Rust table (run after editing data/relic_classes.json, then rebuild)
"""
import json, os, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
sys.path.insert(0, os.path.join(ROOT, "rl"))


def observed(c):
    return c["class"] == "combat" or "combat" in c.get("also", [])


def main():
    import sts2
    names = sts2.names()["relic"]
    cls = json.load(open(os.path.join(ROOT, "data", "relic_classes.json")))["relics"]
    missing = [n for n in names if n not in cls]
    if missing:
        sys.exit(f"relics without a class in data/relic_classes.json: {missing}")
    flags = [observed(cls[n]) for n in names]
    lines = ["//! Generated by `tools/gen_relic_mask.py` from `data/relic_classes.json`: do not edit.",
             "//! `OBSERVED[id]`: the relic acts in combat, so the observation shows it (`docs/rl_redesign.md` M2).",
             "",
             f"pub static OBSERVED: [bool; crate::ids::relic::COUNT] = ["]
    for n, f in zip(names, flags):
        lines.append(f"    {str(f).lower()}, // {n}")
    lines.append("];")
    open(os.path.join(ROOT, "crates", "sts2sim", "src", "relic_mask.rs"), "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
    print(f"{sum(flags)} observed, {len(flags) - sum(flags)} masked of {len(flags)}")


if __name__ == "__main__":
    main()
