#!/usr/bin/env python3
"""Generate relic constants (CanonicalVars: DynamicVars with their base values) from the decompiled source.

Usage: tools/gen_relics.py   (writes crates/sts2sim/src/content/gen_relics.rs)

Each relic with literal-valued `CanonicalVars` becomes `pub mod <slug> { pub const <VAR_NAME>: i32 = n; }` (decimals become
`pub const <VAR_NAME>: Dec`). The var name is the C# `DynamicVars["Name"]` key: `Damage`, `Block`, `Cards`, `Energy`,
`StrengthPower` (for `PowerVar<StrengthPower>`), or the explicit name string. Non-literal values (e.g. counters derived
from state) are skipped. Relic code uses `gen_relics::kunai::CARDS` so no number is transcribed by hand.
"""
import glob, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
DECOMP = os.environ.get("DECOMP", os.path.join(ROOT, "decomp"))
if not os.path.isdir(DECOMP):
    DECOMP = "/home/ytc/Projects/sts2-solver/decomp"
RELICS = os.path.join(DECOMP, "MegaCrit/Sts2/Core/Models/Relics")
OUT = os.path.join(ROOT, "crates/sts2sim/src/content/gen_relics.rs")

src = open(os.path.join(HERE, "gen_ids.py")).read()
ns = {}
exec(src[src.index("def slugify"):src.index("def classes")], {"re": re, "os": os}, ns)
slugify = ns["slugify"]

KIND = {"DamageVar": "Damage", "BlockVar": "Block", "CardsVar": "Cards", "EnergyVar": "Energy", "StarsVar": "Stars",
        "RepeatVar": "Repeat", "HpLossVar": "HpLoss", "HealVar": "Heal", "SummonVar": "Summon", "ForgeVar": "Forge",
        "GoldVar": "Gold", "MaxHpVar": "MaxHp"}


def strip_comments(s):
    s = re.sub(r"/\*.*?\*/", "", s, flags=re.S)
    return re.sub(r"//[^\n]*", "", s)


def match_paren(s, i):
    d = 0
    for j in range(i, len(s)):
        if s[j] == "(":
            d += 1
        elif s[j] == ")":
            d -= 1
            if d == 0:
                return j
    raise ValueError


def split_args(a):
    out, d, cur, instr = [], 0, "", False
    for ch in a:
        if ch == '"':
            instr = not instr
        if not instr and ch in "([{<":
            d += 1
        if not instr and ch in ")]}>":
            d -= 1
        if ch == "," and d == 0 and not instr:
            out.append(cur.strip())
            cur = ""
        else:
            cur += ch
    if cur.strip():
        out.append(cur.strip())
    return out


def screaming(name):
    return slugify(name).replace("-", "_")  # slugify gives UPPER_SNAKE


def parse_vars(body):
    m = re.search(r"CanonicalVars\s*=>", body)
    if not m:
        return []
    # expression extends to the matching end: take until the first ';' at nesting depth 0
    i, d = m.end(), 0
    j = i
    while j < len(body):
        c = body[j]
        if c in "([{":
            d += 1
        elif c in ")]}":
            d -= 1
        elif c == ";" and d == 0:
            break
        j += 1
    expr = body[i:j]
    vars_ = []
    for mm in re.finditer(r"new\s+(\w+)(?:<(\w+)>)?\s*\(", expr):
        cls, gen = mm.group(1), mm.group(2)
        if cls not in KIND and cls not in ("DynamicVar", "PowerVar"):
            continue
        end = match_paren(expr, mm.end() - 1)
        args = split_args(expr[mm.end():end])
        name = None
        if args and args[0].startswith('"'):
            name = args[0].strip('"')
            args = args[1:]
        if cls in KIND:
            name = name or KIND[cls]
        elif cls == "PowerVar":
            name = name or gen
        if name is None or not args:
            continue
        v = args[0]
        vm = re.fullmatch(r"(\d+(?:\.\d+)?)m?", v)
        if not vm:
            continue
        vars_.append((name, vm.group(1)))
    return vars_


def main():
    out = ["// @generated by tools/gen_relics.py from the decompiled game source. Do not edit.", "#![allow(dead_code)]", "use crate::dec::Dec;", ""]
    n = 0
    for path in sorted(glob.glob(os.path.join(RELICS, "*.cs"))):
        s = strip_comments(open(path, encoding="utf-8-sig").read())
        cm = re.search(r"public\s+(?:sealed\s+)?class\s+(\w+)\s*:\s*RelicModel", s)
        if not cm:
            continue
        vs = parse_vars(s)
        if not vs:
            continue
        out.append(f"pub mod {slugify(cm.group(1)).lower()} {{")
        out.append("    #[allow(unused_imports)]\n    use super::*;")
        for name, val in vs:
            c = screaming(name)
            if "." in val:
                digits = len(val.split(".")[1])
                num = val.replace(".", "")
                out.append(f"    pub const {c}: Dec = Dec::frac({int(num)}, {digits});")
            else:
                out.append(f"    pub const {c}: i32 = {val};")
        out.append("}")
        n += 1
    open(OUT, "w").write("\n".join(out) + "\n")
    print(f"wrote {OUT}: {n} relics")


main()
