#!/usr/bin/env python3
"""Writes crates/sts2sim/src/card_powers.rs (observation v3 card effect descriptors): every card is played, at upgrade 0 and 1, as the only card
of a fresh fight against one sturdy powerless enemy; the power changes it causes on the player and the enemy are recorded."""
import json, os, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
sys.path.insert(0, os.path.join(ROOT, "rl"))
CHAR = {"IRONCLAD", "SILENT", "DEFECT", "NECROBINDER", "REGENT"}
TARGET = {"self": 1, "enemy": 2, "all": 3}


def scenario(card, upgrade, character, encounter):
    return dict(name="card_powers", ascension=0, encounter=encounter, character=character, hp=500, max_hp=500, max_energy=9, gold=0, max_potion_slots=0,
                base_orb_slots=3 if character == "DEFECT" else 0, seed="card_powers", total_floor=1, act=0,
                deck=[{"id": card, "upgrade": upgrade}], relics=[], potions=[])


def powers(snap):
    pl = {p["id"]: p["amount"] for p in snap["player"]["powers"]}
    en = [{p["id"]: p["amount"] for p in e["powers"]} for e in snap["enemies"]]
    return pl, en


def find_encounter(sts2, cat):
    best = None
    for e in cat["encounters"] if isinstance(cat["encounters"], list) else cat["encounters"].keys():
        name = e if isinstance(e, str) else e.get("id")
        try:
            snap = json.loads(sts2.Sim(json.dumps(scenario("STRIKE_IRONCLAD", 0, "IRONCLAD", name)), 1).snapshot())
        except Exception:  # noqa: BLE001
            continue
        en = snap["enemies"]
        if len(en) == 1 and not en[0]["powers"] and en[0]["hp"] >= 100 and (best is None or en[0]["hp"] > best[1]):
            best = (name, en[0]["hp"])
    return best[0]


def play_once(sts2, card, upgrade, character, encounter):
    sim = sts2.Sim(json.dumps(scenario(card, upgrade, character, encounter)), 1)
    if sim.stage() != "play":
        return None
    pl0, en0 = powers(json.loads(sim.snapshot()))
    plays = [(i, s) for i, s in sim.legal() if s.startswith("play")]
    if not plays:
        return None
    sim.step(plays[0][0])
    for _ in range(20):
        if sim.stage() != "choice":
            break
        sim.step(sim.legal()[0][0])
    pl1, en1 = powers(json.loads(sim.snapshot()))
    out = {}
    for k in set(pl0) | set(pl1):
        if pl1.get(k, 0) != pl0.get(k, 0):
            out[(k, "self")] = pl1.get(k, 0) - pl0.get(k, 0)
    if en0 and en1:
        for k in set(en0[0]) | set(en1[0]):
            if en1[0].get(k, 0) != en0[0].get(k, 0):
                out[(k, "enemy")] = en1[0].get(k, 0) - en0[0].get(k, 0)
    return out


def main():
    import sts2
    names = sts2.names()
    cards, pnames = names["card"], names["power"]
    pid = {n: i for i, n in enumerate(pnames)}
    cat = json.load(open(os.path.join(ROOT, "data", "catalog.json")))
    info = {c["id"]: (pool, c) for pool, lst in cat["cards"].items() for c in lst}
    enc = find_encounter(sts2, cat)
    rows, n_eff = [], 0
    for name in cards:
        pool, c = info.get(name, ("IRONCLAD", {}))
        eff = []
        if c and not c.get("x") and not c.get("multiplayer_only"):
            ch = pool if pool in CHAR else "IRONCLAD"
            r = [play_once(sts2, name, u, ch, enc) if u <= c.get("max_upgrade", 0) else None for u in (0, 1)]
            if r[0]:
                tgt_all = c.get("target") == "AllEnemies"
                same = name + "_POWER"
                keys = sorted(r[0], key=lambda k: (k[0] != same, list(r[0]).index(k)))
                for k in keys[:2]:
                    a0 = r[0][k]
                    a1 = (r[1] or {}).get(k, a0) if r[1] is not None else a0
                    side = "all" if k[1] == "enemy" and tgt_all else k[1]
                    eff.append((pid[k[0]] + 1, TARGET[side], a0, a1))
        n_eff += bool(eff)
        eff += [(0, 0, 0, 0)] * (2 - len(eff))
        rows.append((name, eff))
    lines = ["//! Generated by `tools/gen_card_powers.py`: do not edit.",
             "//! Per card: up to two (power id + 1, target 1 self / 2 one enemy / 3 all enemies, amount at upgrade 0, amount at upgrade 1) that playing it applies on a fresh fight.",
             f"//! Fight: the card alone in the deck, 9 energy, against {enc}.",
             "",
             "pub static CARD_POWERS: [[(u16, u8, i16, i16); 2]; crate::ids::card::COUNT] = ["]
    for name, eff in rows:
        lines.append("    [" + ", ".join(f"({p}, {t}, {a}, {b})" for p, t, a, b in eff) + f"], // {name}")
    lines.append("];")
    open(os.path.join(ROOT, "crates", "sts2sim", "src", "card_powers.rs"), "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
    print(f"{n_eff} of {len(cards)} cards apply powers (encounter {enc})")


if __name__ == "__main__":
    main()
