#!/usr/bin/env python3
"""Run differential sweeps over potion pairs (A10: 2 potion slots) with a ported-cards Ironclad deck.

  tools/potion_sweep.py [--n 12] [--hp 80] [--cur-hp 30] [--encounter NIBBITS_WEAK] [--lenient] A_POTION,B_POTION ...
  tools/potion_sweep.py --all            # every potion paired with a rotating companion (2 pairs each)

`--lenient` sets STS2DIFF_LENIENT=1 (unported cards generated by a potion do not stop the replay; only divergences on
LATER steps are tolerated and reported as UNIMPLEMENTED).
"""
import argparse, json, os, subprocess, sys, tempfile

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
DECK = ("ANGER,ARMAMENTS,TRUE_GRIT,HEADBUTT,BURNING_PACT,THUNDERCLAP,"
        "SWORD_BOOMERANG,CINDER,BLOODLETTING,INFLAME,TWIN_STRIKE,IRON_WAVE,SHRUG_IT_OFF,POMMEL_STRIKE")
ALL = [
    "AMBERGRIS", "ASHWATER", "ATTACK_POTION", "BEETLE_JUICE", "BLESSING_OF_THE_FORGE", "BLOCK_POTION", "BLOOD_POTION",
    "BOTTLED_POTENTIAL", "CLARITY", "COLORLESS_POTION", "COSMIC_CONCOCTION", "CUNNING_POTION", "CURE_ALL", "DEXTERITY_POTION",
    "DISTILLED_CHAOS", "DROPLET_OF_PRECOGNITION", "DUPLICATOR", "ENERGY_POTION", "ENTROPIC_BREW", "EXPLOSIVE_AMPOULE",
    "FAIRY_IN_A_BOTTLE", "FIRE_POTION", "FLEX_POTION", "FOCUS_POTION", "FORTIFIER", "FOUL_POTION", "FRUIT_JUICE", "FYSH_OIL",
    "GAMBLERS_BREW", "GHOST_IN_A_JAR", "GIGANTIFICATION_POTION", "GLOWWATER_POTION", "HEART_OF_IRON", "LIQUID_BRONZE",
    "LIQUID_MEMORIES", "LUCKY_TONIC", "MAZALETHS_GIFT", "OROBIC_ACID", "POISON_POTION", "POTION_OF_BINDING",
    "POTION_OF_CAPACITY", "POTION_OF_DOOM", "POTION_SHAPED_ROCK", "POT_OF_GHOULS", "POWDERED_DEMISE", "POWER_POTION",
    "RADIANT_TINCTURE", "REGEN_POTION", "SHACKLING_POTION", "SHIP_IN_A_BOTTLE", "SKILL_POTION", "SNECKO_OIL", "SOLDIERS_STEW",
    "SPEED_POTION", "STABLE_SERUM", "STAR_POTION", "STRENGTH_POTION", "SWIFT_POTION", "TOUCH_OF_INSANITY", "VULNERABLE_POTION",
    "WEAK_POTION",
]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("pairs", nargs="*")
    ap.add_argument("--all", action="store_true")
    ap.add_argument("--n", type=int, default=12)
    ap.add_argument("--hp", type=int, default=80)
    ap.add_argument("--cur-hp", type=int, default=None, help="starting current HP (max stays --hp)")
    ap.add_argument("--encounter", default="NIBBITS_WEAK")
    ap.add_argument("--relics", default="")
    ap.add_argument("--lenient", action="store_true")
    ap.add_argument("--jobs", type=int, default=14)
    ap.add_argument("--deck", default=DECK)
    a = ap.parse_args()
    pairs = [p.split(",") for p in a.pairs]
    if a.all:
        for i, p in enumerate(ALL):
            for off in (1, 7):
                pairs.append([p, ALL[(i + off) % len(ALL)]])
    env = dict(os.environ)
    if a.lenient:
        env["STS2DIFF_LENIENT"] = "1"
    tmp = tempfile.mkdtemp(prefix="potsweep")
    bad = 0
    for pr in pairs:
        t = subprocess.run([sys.executable, os.path.join(ROOT, "tools/mk_scenario.py"), "--encounter", a.encounter, "--starter",
                            "--deck", a.deck,
                            "--potions", ",".join(pr), "--hp", str(a.hp), "--relics", a.relics],
                           capture_output=True, text=True)
        if t.returncode != 0:
            print(pr, "mk_scenario failed", t.stderr[-200:])
            continue
        s = json.loads(t.stdout)
        if a.cur_hp is not None:
            s["hp"] = a.cur_hp
        path = os.path.join(tmp, "_".join(pr) + ".json")
        json.dump(s, open(path, "w"))
        r = subprocess.run([sys.executable, os.path.join(ROOT, "tools/diff_sweep.py"), path, "--n", str(a.n), "--jobs", str(a.jobs),
                            "--keep", os.path.join(tmp, "out"), "--tag", "_".join(p[:4] for p in pr) + "_"], capture_output=True, text=True, env=env)
        lines = r.stdout.strip().splitlines()
        summ = [l for l in lines if l.startswith("SUMMARY")]
        flag = "" if r.returncode == 0 else "  <<<<<<<< FAIL"
        if r.returncode != 0:
            bad += 1
        print(",".join(pr), "->", (summ[-1][8:60] if summ else "?"), flag, flush=True)
        for l in lines:
            if l.startswith("UNIMPLEMENTED content hit"):
                print("    ", l[:300])
        if r.returncode != 0:
            for l in lines[:14]:
                if not l.startswith("SUMMARY"):
                    print("    ", l[:400])
    print("pairs failing:", bad, "artifacts:", tmp)


main()
